### ISSUE TITLE
.dll source

### ISSUE THREAD

**Issue by ghost** [NYAN-x-CAT/Lime-Miner#5]
Hello, can i get project1.dll source pls :)

**Comment by NYAN-x-CAT** [comment]
Hmm, I guess I forgot to add the link sorry.
https://github.com/gigajew/WinXRunPE-x86_x64
Use 64bit

**Comment by onishn96** [comment]
Hi I am trying something but my application is just working in debugging. I'm building and starting my application but it doesn't work. Could you please help me? Picture link https://ibb.co/FghW9jv

**Comment by NYAN-x-CAT** [comment]
Build it 64bit.

**Comment by onishn96** [comment]
still same problem :( New Picture Link https://ibb.co/jkWXw0c

**Comment by onishn96** [comment]
bro could you help me please? im building 64bit but still same problem and i dont know why ^^
Windows 10 Home Single Lang..
