### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by jotidd** [NYAN-x-CAT/Lime-Miner#7]
v1 ..brilliant on all computers no problems whatsoever but v3 is crashing with system access violation exception on the ones I have tried it on.  Cant get to the bottom of it.  Tried win7 to win 10.  Hope you can help as i love it.

**Comment by jotidd** [comment]
That is the miner crashing not the builder.

**Comment by NYAN-x-CAT** [comment]
@jotidd miner work on 64bit windows.
